apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.api_server }}
  project: kube-system
  source:
    path: argocd/argocd-apps/cluster-apps
    repoURL: {{ .Values.github_repo_url }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      version: v3